FROM mysql

ENV MYSQL_ROOT_PASSWORD=123

ENV MYSQL_USER=API

ENV MYSQL_PASSWORD=webDataViz0API

RUN git clone https://github.com/Insight-Trip/MySQL.git

RUN rm README.md

COPY MySQL /docker-entrypoint-initdb.d

EXPOSE 3306
