FROM amazoncorretto:21.0.5-al2023-headless
WORKDIR /app
COPY ./AlgoritmoLog-2.0-SNAPSHOT-jar-with-dependencies.jar .
COPY ./.env .
ENTRYPOINT ["java", "-jar", "AlgoritmoLog-2.0-SNAPSHOT-jar-with-dependencies.jar"]