name: it-app
services:
  db:
    image: matheusos2002/bd_it:v1
    environment:
      - "MYSQL_USER:InsertOnly"
      - "MYSQL_PASSWORD:123456"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db-data:/etc/data
    networks:
      - backend
  site:
    image: matheusos2002/site_it:v1
    ports:
      - "3333:3333"
    expose:
      - "3333"
    depends_on:
      - db
    links:
      - db
    networks:
    - backend
  java:
    image: matheusos2002/java_it:v1
    restart: on-failure
    depends_on:
      - db
    links:
      - db
    networks:
      - backend
networks:
  backend:
volumes:
  db-data:
